#----------------------------------------
# Slash-Bar webapp mapping
#----------------------------------------

# この設定ファイルは url path 上の `/-` という部分を `.webapp/public` へと置き換えます
# これにより、アプリのディレクトリの中の public/ だけを外部へ見せることが出来ます。

AliasMatch ^/-/(?!static/|cgi-bin/)(.*)?$    /usr/local/apache2/yatt.webapp/public/$1
AliasMatch ^/-/cgi-bin/(.*)?$    /usr/local/apache2/yatt.webapp/cgi-bin/$1
AliasMatch ^/-/static/(.*)?$    /usr/local/apache2/yatt.webapp/static/$1

<Directory "/usr/local/apache2/yatt.webapp">
 #deny from all
 Require all denied
 Options -ExecCGI -FollowSymLinks -Indexes -Multiviews -Includes -IncludesNOEXEC
 AllowOverride All Options=All,Multiviews
</Directory>

<DirectoryMatch "^/usr/local/apache2/yatt((?:/[^-/\.]+?(?:-[^/\.]*?)?)*?).webapp/cgi-bin">
 #allow from all
 Require all granted
 Options +ExecCGI
 AddHandler cgi-script .cgi
</DirectoryMatch>

<DirectoryMatch "^/usr/local/apache2/yatt((?:/[^-/\.]+?(?:-[^/\.]*?)?)*?).webapp/(static|public)">
 #allow from all
 Require all granted
</DirectoryMatch>

#----------------------------------------
# /usr/local/apache2/yatt/**/*.webapp も有効にしたい場合

# 安全のため、 ** の箇所には↓下記のパターンのみ許可
# ((?:/[^-/\.]+?(?:-[^/\.]*?)?)*?)

# PATH            $1
# /-/             ''
# /foo/-/         /foo
# /foo-bar/-/     /foo-bar

AliasMatch ^((?:/[^-/\.]+?(?:-[^/\.]*?)?)*?)/-/(?!static/|cgi-bin/)(.*)?$    /usr/local/apache2/yatt$1.webapp/public/$2
AliasMatch ^((?:/[^-/\.]+?(?:-[^/\.]*?)?)*?)/-/cgi-bin/(.*)?$    /usr/local/apache2/yatt$1.webapp/cgi-bin/$2
AliasMatch ^((?:/[^-/\.]+?(?:-[^/\.]*?)?)*?)/-/static/(.*)?$    /usr/local/apache2/yatt$1.webapp/static/$2

<Directory "/usr/local/apache2/yatt">
 #deny from all
 Require all denied
 Options -ExecCGI -FollowSymLinks -Indexes -Multiviews -Includes -IncludesNOEXEC
 AllowOverride All Options=All,Multiviews
</Directory>
